### PR TITLE
Add cross-compiling sample stack and builder for armv6

### PR DESCRIPTION
**Pull request by jromero**

### CODE REVIEW

**Comment by jromero** [comment]
**"works on my machine"**

This is likely a symptom due to the fact that the CPU on my machine and the way Docker handles architecture allows for this to work locally but not in the way that the GitHub Actions worker is configured. Will investigate further.

**Comment by zmackie** [comment]
This is awesome.  I was wondering about non-x86 architectures, and you've gone and done it!

**Comment by jromero** [comment]
A few more attempts at trying to get this to build in GH Actions. I'm able to get it to build [using `buildx`](https://github.com/alexellis/openfaas-actions-multiarch/blob/55d83137a51d2cd93fd4187d2b670dc97b80b550/.github/workflows/main.yml) but it seems like the images [can't be hosted on the local daemon](https://github.com/docker/buildx/issues/166#issuecomment-544827163) making it not workable for the purpose of testing. It could still work for deploying to docker hub directly but can't be otherwise tested without a custom runner so far.

**Comment by jromero** [comment]
Closing this for now as it's not of high priority.

**Pull request closed without merging**
