### PR TITLE
Add a few example homepages in buildpacks

### PR DESCRIPTION
**Pull request by zmackie**
Signed-off-by: Zander Mackie <zmackie@gmail.com>

### CODE REVIEW

**Comment by jromero** [comment]
Out of curiosity, is there a reason why we wouldn't include it in all of them?

**Comment by zmackie** [comment]
> Out of curiosity, is there a reason why we wouldn't include it in all of them?

Nope. I thought it might be overkill but happy to add to all.

**Comment by jromero** [comment]
> > Out of curiosity, is there a reason why we wouldn't include it in all of them?
> 
> Nope. I thought it might be overkill but happy to add to all.

Great! Could you? It would be nice, visually, to have all of them.

**Comment by zmackie** [comment]
@jromero Done.

**Pull request merged**
