### PR TITLE
Build from released pack

### PR DESCRIPTION
**Pull request by AidanDelaney**
Revert back to getLatestRelease

### CODE REVIEW

**Review by natalieparellano — APPROVED** [review]

**Review by jjbustamante — APPROVED** [review]
LGTM, but @AidanDelaney  there is a conflict file that needs to be fix 😄

**Comment by AidanDelaney** [comment]
I'll fix the conflict when we release `0.31.0`.  We currently use a pre-release of `0.31.0`.

**Comment by AidanDelaney** [comment]
@jkutner Could you review this please?

**Comment by jjbustamante** [comment]
@AidanDelaney @natalieparellano What do we need to get this one merged? I think using the latest version will help me with tests for `0.34.0` :)

**Review by natalieparellano — APPROVED** [review]

**Review by jkutner — APPROVED** [review]

**Pull request merged**
