### PR TITLE
Add sample registry

### PR DESCRIPTION
**Pull request by jromero**
Also includes:

- A script to "run" the cnb registry locally.
- A script to update the sample repo.

### CODE REVIEW

**Comment by jkutner** [comment]
I worry about trying to support the shell scripts because they won't work on Windows.

Also, this isn't a registry you'll be able to publish to with `pack publish-buildpack` as described in https://github.com/buildpacks/rfcs/pull/75 so it might confuse people (static registries like this are kind of meant to be an advanced feature).

**Comment by zmackie** [comment]
What's the learning objective here? Is the idea that users would generally host their own registries? Maybe we should just reserve `samples` in the public registry and push these there?

**Comment by jromero** [comment]
> Maybe we should just reserve samples in the public registry and push these there?

For sure this should be an end goal. Unfortunately we don't have the registry just yet.

> Also, this isn't a registry you'll be able to publish to with pack publish-buildpack as described in buildpacks/rfcs#75 so it might confuse people (static registries like this are kind of meant to be an advanced feature).
>
> ---
>
> What's the learning objective here? Is the idea that users would generally host their own registries?

I'll try to answer both of these questions as one. My initial intent was to have a stepping stone to what the `registry:2` docker image is. I think it would be valuable for the community to be able to stand up a registry for things such as the user acceptance we had to run but most importantly for integrations. The same reasons why we, and the use cases others have, to use `registry:2` are the reasons why we should aim to provide the same.

That said, I see the concern of this being in samples instead of maybe it's own tested implementation.

> I worry about trying to support the shell scripts because they won't work on Windows.

Heard. I'll rethink the implementation.

**Comment by zmackie** [comment]
@jromero I think this is a really good reason for this to exist (and maybe as its own repo, as you said):
> I'll try to answer both of these questions as one. My initial intent was to have a stepping stone to what the registry:2 docker image is. I think it would be valuable for the community to be able to stand up a registry for things such as the user acceptance we had to run but most importantly for integrations. The same reasons why we, and the use cases others have, to use registry:2 are the reasons why we should aim to provide the same.

**Pull request closed without merging**
